#!/usr/bin/env node

const { boxify, print } = require('foxy-dev-tools');
const highlight = require('./highlight.js');
const readFile = require('./helpers.js');
const aboutParrotJS = require('./about-parrot-js.js');

function hi(code) {
    const highlightedSourceCode = highlight(code);
    console.log(highlightedSourceCode);
}

const FILENAME_PROVIDED_IN_CALL = 3;
if(process.argv.length === FILENAME_PROVIDED_IN_CALL) {
    const sourceCode = readFile(process.argv[2]);
    hi(sourceCode);
} else if(process.stdin.isTTY !== undefined) { 
    const boxifiedText = boxify(aboutParrotJS.split('\n'));
    boxifiedText.forEach((ln) => print(ln, 'black', 'white'));
    process.exit(1);
} else {
    const stdin = process.openStdin();
    let data = '';
    stdin.on('data', (chunk) => data += chunk);
    stdin.on('end', () => hi(data));
}

