#!/usr/bin/env node

const { readFileSync } = require('fs');
const highlight = require('./highlight.js');
const sourceCodeRegExp = require('./source-code-reg-exp.js');

if(process.argv.length !== 3) {
    console.log('No input.');
    process.exit(1);
}

function readFile(fileName) {
    try {
        return readFileSync(fileName, 'utf8');
    } catch (errorMessage) {
        throw new Error(errorMessage);
    }
}

process.stdout.write(
    readFile(process.argv[2]).replace(
        sourceCodeRegExp, 
        highlight
    )
);

