#!/usr/bin/env node

const highlight = require('./highlight.js');
const readFile = require('./helpers.js');

const FILE_IN_CALL = 3;
if(process.argv.length !== FILE_IN_CALL) {
    console.log('No input.');
    process.exit(1);
}
let sourceCode = readFile(process.argv[2]);
const highlightedSourceCode = highlight(sourceCode);
process.stdout.write(highlightedSourceCode);

